
import Head from 'next/head'

// CSS
import '../styles/style.css'

// Bootstrap
import 'bootstrap/dist/css/bootstrap.min.css';



function MyApp({ Component, pageProps }) {

  return (

    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Dream product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="images/logo.png" />
      </Head>

        <Component {...pageProps} />
        
    </>
  );
}

export default MyApp;
